name: Pulimi - Check

on:
  pull_request:
    branches:
      - "main"

jobs:
  Preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure node
        id: configure_node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        id: install_pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        id: install_dependencies
        run: |
          pnpm install

      - name: Configure AWS Credentials
        id: configure_aws_credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run Pulumi
        id: run-polumi
        uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: stg
          cloud-url: s3://pos-tech-360-pulumi-state-andre-wronscki
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          PULUMI_CONFIG_PASSPHRASE: ""
